# Generated by Django 3.1.14 on 2023-07-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_store_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
